var myFullName;
console.log("My Full Name is :", myFullName);
myFullName = "chitta";
console.log("My first Name", myFullName);
myFullName = "swain";
console.log("my Last Name is :", myFullName);
var myLove = "i Love only js";
console.log("my love :", myLove);
var firstName = "chitta";
console.log("My first Name :", firstName);
var lastName = "Swain";
console.log("My last name :", lastName);
var age = "22";
console.log("My age :", age);
var address = "Odisha";
console.log("My address :", address);
var gender = "Male";
console.log("gender :", gender);
var isMarried = "No";
console.log("married :", isMarried);
